name: Build LobeHub for Serv00
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # 暂时关闭缓存以避免报错
          # cache: 'pnpm' 

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build project
        run: pnpm run build
        env:
          NEXT_PUBLIC_SERVICE_MODE: server

      - name: Prepare Artifact
        run: |
          mkdir release
          cp -r .next release/
          cp -r public release/
          cp package.json release/
          zip -r lobehub-serv00.zip release/

      - name: Upload Zip
        uses: actions/upload-artifact@v4
        with:
          name: lobehub-build-package
          path: lobehub-serv00.zip
